# Generated by Django 4.1.3 on 2022-11-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
