# Generated by Django 4.1.3 on 2022-11-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_user_birth_date_user_gender_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Мужской"), ("female", "Женский")],
                max_length=10,
                null=True,
            ),
        ),
    ]
